version: "3.0"

services:

  api:
    container_name: api_helpsystem
    hostname: helpsystem-api
    image: gchsantos/helpsystem_api:latest
    command: './start-server.sh'
    environment:
      DJANGO_SETTINGS_MODULE: helpsystem_api.settings.production
      MODE: PROD
    volumes:
      - "api-dbdata:/app/db"
    ports:
      - 8000:8000
    networks:
      - backend

  frontend:
    container_name: frontend_helpsystem
    hostname: frontend
    image: gchsantos/helpsystem_frontend:latest
    command: 'npm run start'
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend

volumes:
  api-dbdata:

networks:
  frontend:
  backend:
